version: '3.8'

services:
  db:
    image: mysql:8.0.26
    container_name: scheduler-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mentorship
      MYSQL_USER: fnkaya
      MYSQL_PASSWORD: obss
    ports:
      - '3306:3306'